# Generated by Django 3.0.10 on 2020-09-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLATable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.IntegerField(default=1)),
                ('priority1', models.IntegerField(default=1)),
                ('priority2', models.IntegerField(default=1)),
                ('priority3', models.IntegerField(default=1)),
                ('priority4', models.IntegerField(default=1)),
                ('FRT1', models.IntegerField(default=15)),
                ('ERT1', models.IntegerField(default=1)),
                ('RT1', models.IntegerField(default=1)),
                ('Hours1', models.IntegerField(default=1)),
                ('FRT2', models.IntegerField(default=15)),
                ('ERT2', models.IntegerField(default=1)),
                ('RT2', models.IntegerField(default=1)),
                ('Hours2', models.IntegerField(default=1)),
                ('FRT3', models.IntegerField(default=15)),
                ('ERT3', models.IntegerField(default=1)),
                ('RT3', models.IntegerField(default=1)),
                ('Hours3', models.IntegerField(default=1)),
                ('FRT4', models.IntegerField(default=15)),
                ('ERT4', models.IntegerField(default=1)),
                ('RT4', models.IntegerField(default=1)),
                ('Hours4', models.IntegerField(default=1)),
                ('Title', models.CharField(max_length=255)),
                ('Timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('Day', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Holiday', models.CharField(blank=True, max_length=255, null=True)),
                ('MonST', models.TimeField(blank=True, null=True)),
                ('TueST', models.TimeField(blank=True, null=True)),
                ('WedST', models.TimeField(blank=True, null=True)),
                ('ThurST', models.TimeField(blank=True, null=True)),
                ('FriST', models.TimeField(blank=True, null=True)),
                ('MonET', models.TimeField(blank=True, null=True)),
                ('TueET', models.TimeField(blank=True, null=True)),
                ('WedET', models.TimeField(blank=True, null=True)),
                ('ThurET', models.TimeField(blank=True, null=True)),
                ('FriET', models.TimeField(blank=True, null=True)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
