# Generated by Django 3.0.10 on 2020-10-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLA', '0002_auto_20201001_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Holiday', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slatable',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='slatable',
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='slatable',
            name='Hours1',
        ),
        migrations.RemoveField(
            model_name='slatable',
            name='Hours2',
        ),
        migrations.RemoveField(
            model_name='slatable',
            name='Hours3',
        ),
        migrations.RemoveField(
            model_name='slatable',
            name='Hours4',
        ),
    ]
