# Generated by Django 3.0.10 on 2020-10-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('SLA', '0006_delete_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_val', models.IntegerField(blank=True, null=True)),
                ('priority_name', models.CharField(blank=True, max_length=50, null=True)),
                ('FRT', models.IntegerField(blank=True, null=True)),
                ('ERT', models.IntegerField(blank=True, null=True)),
                ('RT', models.IntegerField(blank=True, null=True)),
                ('company_link', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.Company')),
            ],
        ),
    ]
