# Generated by Django 3.0.10 on 2020-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SLA', '0009_auto_20201006_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='company_link',
        ),
        migrations.RemoveField(
            model_name='urgency',
            name='company_link',
        ),
        migrations.RemoveField(
            model_name='urgency',
            name='priority_link',
        ),
        migrations.DeleteModel(
            name='Impact',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.DeleteModel(
            name='Urgency',
        ),
    ]
