# Generated by Django 3.0.10 on 2020-10-06 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='last_ticket',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
