# Generated by Django 3.0.10 on 2020-10-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_group_company_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='round_robin_selected',
            field=models.BooleanField(default=False),
        ),
    ]
