# Generated by Django 3.0.10 on 2020-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_technician_round_robin_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
