# Generated by Django 3.0.10 on 2020-10-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_company_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='company_link',
        ),
    ]
