# Generated by Django 3.0.10 on 2020-10-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('incident_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
